name: Supabase DB Push

on:
  push:
    paths:
      - "supabase/migrations/**"
      - ".github/workflows/supabase-db-push.yml"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Supabase CLI version
        run: supabase --version

      - name: Sanity check DSN host
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: echo "$SUPABASE_DB_URL" | sed -E 's#^postgresql://[^@]*@([^:/?]+).*#Host=\1#'
      
      - name: Apply migrations to Supabase
        env:
          SUPABASE_DB_URL_BASE: ${{ secrets.SUPABASE_DB_URL_BASE }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          
        run: |
          supabase db push --db-url "$SUPABASE_DB_URL_BASE" --include-all -p "$SUPABASE_DB_PASSWORD"
