name: Supabase DB Push

on:
  push:
    paths:
      - "supabase/migrations/**"
      - ".github/workflows/supabase-db-push.yml"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Supabase CLI version
        run: supabase --version

      - name: Apply migrations to Supabase
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          supabase db push --db-url "$SUPABASE_DB_URL" --include-all
          # Se precisar debugar:
          # supabase db push --db-url "$SUPABASE_DB_URL" --include-all --debug
